# Use root/example user/password credentials
version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./project/:/var/www/html/

  db: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
     # Funkar med sådan här typ av nätverksconfig i enkla fall. Men man vill nog titta in på namnbaserad för större CI/CD system /mvh Sebastian:
     # https://medium.com/capital-one-tech/connect-to-a-mysql-docker-container-without-using-a-static-ip-address-2d76a7f933a3
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes: 
  mysql-data:
